--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BeginnerCoder3/Ultimate-Nicknames
build-by-default: true
branches:
- main
projects:
  Ultimate-Nicknames:
    path: "Ultimate-Nicknames/OIP.HU0W4a2Y9nqRfiXG7BT78wHaGl.jpg"
...
