---
name: Ultimate_Nicknames
version: 0.9.2
main: muziekmystro\Ultimate_Nicknames\Main
api: [3.0.0]
author: muziekmystro

commands:
  nick:
    description: Change your nickname!
    aliases: [nickname]
    permission: un.nick

  unnick:
    description: Go back to your default name!
    aliases: [unnickname]
    permission: un.unnick

permissions:
  un.nick:
    description: Allows a player to nick.
    default: true
  un.unnick:
    description: Allows a player to unnick.
    default: true
...
